### PR TITLE
Pull daily builds from nyftp.netbsd.org, via HTTPS.

### PR DESCRIPTION
**Pull request by bsiegert**

### CODE REVIEW

**Comment by gson1703** [comment]
The existing code is wrong, but the fix should be to make the code match the documentation on the NetBSD web site, which points to http://nycdn.NetBSD.org/pub/NetBSD-daily/ (from http://www.netbsd.org/releases/current.html via http://releng.netbsd.org/cgi-bin/builds.cgi).

Also please note that the DailyBuild class is deprecated and I ought to mark it as such.  The recommended way to point anita at a daily build when calling it as a Python library is using the anita.URL class.

**Comment by gson1703** [comment]
Actually, it looks like the DailyBuild class has been broken since at least 2011 because it lacks a mi_url() method. Since clearly no one is using it, I should just remove it.

**Comment by bsiegert** [comment]
I would also be fine with that :)
gson1703 <notifications@github.com> schrieb am Mi. 1. Aug. 2018 um 12:48:

**Comment by bsiegert** [comment]
This pull request is now obsolete with 2daff93a5840ab64198e0c4f4edd3510f5fbf8d4.

**Pull request closed without merging**
